Delete images and networks on exit
If you want to run more than one test the actual way in which this
validation ends does not delete the network and the images that were
created by the script.
For example if you want to create a new network on on the same device as
the "nova" one that is created by the validation, you get an error.
So I removed the deletes that were done before launching single commands
(since we're starting from a clean env there's no need to clean
anything) and I added a full clean on the cleanup function (called when
exiting).

Change-Id: I4342897dc88424a119a9668698668972caf03676

diff --git a/templates/overcloud-validate.sh.j2 b/templates/overcloud-validate.sh.j2
--- a/templates/overcloud-validate.sh.j2
+++ b/templates/overcloud-validate.sh.j2
@@ -20,11 +20,18 @@ function cleanup() {
         {% endif %}
         fi
     fi
+    # Remove images and network
+    rm -f {{ validate_image_dir }}/cirros.*
+    glance image-list | grep pingtest | awk '{print $2}' | while read IMAGEID; do glance image-delete $IMAGEID; done
+    #neutron net-delete {{ overcloud_public_network_name }} > /dev/null 2>&1 || true
+    neutron net-delete {{ overcloud_public_network_name }}
 }
 # trap on exit
 trap cleanup EXIT
 # source tenantrc file
 source {{ working_dir }}/{{ tenantrc }}
+# Check if an environment is already deployed and, in case, cleanup it
+[ "x$(heat stack-list | grep pingtest_stack || true)" != "x" ] && cleanup
 # get validate image
 if [[ ! -d {{ validate_image_dir }} ]]; then
     mkdir {{ validate_image_dir }};
@@ -35,17 +42,11 @@ KERNEL_PATH={{ validate_image_dir }}/cirros.kernel
 curl -L -o $IMAGE_PATH {{ validate_image_url }}{{ image_disk }}
 curl -L -o $INITRAMFS_PATH {{ validate_image_url }}{{ image_initramfs }}
 curl -L -o $KERNEL_PATH {{ validate_image_url }}{{ image_kernel }}
-# remove existing image
-for image in $(glance image-list | grep {{ validate_image_name }} | awk '{ print $2; }'); do
-   glance image-delete $image
-done
 # upload cirros image into glance
 ramdisk_id=$(openstack image create pingtest_initramfs --public --container-format ari --disk-format ari --file $INITRAMFS_PATH | grep ' id ' | awk '{print $4}')
 kernel_id=$(openstack image create pingtest_kernel --public --container-format aki --disk-format aki --file $KERNEL_PATH | grep ' id ' | awk '{print $4}')
 openstack image create {{ validate_image_name }} --public --container-format ami --disk-format ami \
     --property kernel_id=$kernel_id --property ramdisk_id=$ramdisk_id --file $IMAGE_PATH
-# clean up network if it exists from previous run
-neutron net-delete {{ overcloud_public_network_name }} > /dev/null 2>&1 || true
 # create external network
 # Liberty compat :
 #( note: heat can't create an external network in liberty)
