Output a correct value in the log
Previously, it was just stating "error with openstack" for any failure,
instead of pointing to the actual job.

Change-Id: I443debe5cbbb7c1ff8fad21236f16574c23ff83f

diff --git a/roles/validate-undercloud/templates/undercloud-sanity-check.sh.j2 b/roles/validate-undercloud/templates/undercloud-sanity-check.sh.j2
--- a/roles/validate-undercloud/templates/undercloud-sanity-check.sh.j2
+++ b/roles/validate-undercloud/templates/undercloud-sanity-check.sh.j2
@@ -31,7 +31,7 @@ function citest {
     "$@"
     local status=$?
     if [ $status -ne 0 ]; then
-        echo "error with $1" >&2
+        echo "error with ${test_name}" >&2
         generate-subunit $(date +%s) 10 fail $test_name >> {{ working_dir }}/undercloud_sanity.subunit
         script_return_value=1
     else
