Update DLRN command line usage
When building packages with DLRN, we should stop using the undocumented
DELOREAN_DEV environment variable. To check the build result, we can
get the dlrn error code instead of reading the sqlite3 database.

Also, the updated command name is dlrn. Although "delorean" will work,
it is deprecated.

Change-Id: I772b66b83ac0ab0d60ff810d917bdfd84752d285

diff --git a/roles/build-test-packages/tasks/dlrn-build.yml b/roles/build-test-packages/tasks/dlrn-build.yml
--- a/roles/build-test-packages/tasks/dlrn-build.yml
+++ b/roles/build-test-packages/tasks/dlrn-build.yml
@@ -35,18 +35,22 @@
 
 - name: Run DLRN
   shell: >
+    set +e
     source {{ ansible_user_dir }}/dlrn-venv/bin/activate;
     while true; do
-        delorean --config-file projects.ini --head-only --package-name {{ project_name_mapped.stdout }} --local --info-repo rdoinfo --build-env DELOREAN_DEV=1 || /bin/true;
-        STATUS=$(echo "select status from commits where project_name == '{{ project_name_mapped.stdout }}' order by id desc limit 1;" | sqlite3 commits.sqlite);
-        if [ "$STATUS" == "FAILED" ] ; then
-            exit 1;
-        elif [ "$STATUS" == "SUCCESS" ] ; then
+        dlrn --config-file projects.ini --head-only --package-name {{ project_name_mapped.stdout }} --local --info-repo rdoinfo --dev
+        if [ $? -eq 0 ]; then
+            # SUCCESS
             break;
-        elif [ "$STATUS" == "RETRY" ] ; then
+        elif [ $? -eq 1 ]; then
+            # FAILED
+            exit 1;
+        elif [ $? -eq 2 ]; then
+            # RETRY
             continue;
-        fi;
-        exit 1;
+        fi
+        # Unexpected DLRN return code
+        exit $?;
     done;
   args:
       chdir: '{{ ansible_user_dir }}/DLRN'
